# Generated by Django 5.2 on 2025-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='MXN', max_length=3),
        ),
    ]
